# Generated by Django 3.2.5 on 2021-08-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '__first__'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=20000)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ManyToManyField(related_name='answered_by_list', to='accounts.UserProfile')),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_by', to='accounts.userprofile')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_department', to='structure.department')),
                ('down_vote', models.ManyToManyField(related_name='questions_down_votes', to='accounts.UserProfile')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_faculty', to='structure.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_subject', to='structure.subject')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_university', to='structure.university')),
                ('up_vote', models.ManyToManyField(related_name='question_up_votes', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=20000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_by', to='accounts.userprofile')),
                ('down_vote', models.ManyToManyField(related_name='answer_down_votes', to='accounts.UserProfile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answered', to='questions.question')),
                ('up_vote', models.ManyToManyField(related_name='answer_up_votes', to='accounts.UserProfile')),
            ],
        ),
    ]
